export const HOSPITALS = [
  "Kenyatta National Hospital",
  "Aga Khan University Hospital",
  "Nakuru Level 5 Hospital",
  "Mater Misericordiae Hospital",
  "Moi Teaching and Referral Hospital",
  "Coast General Hospital",
  "Gertrude's Children's Hospital",
  "Karen Hospital",
  "MP Shah Hospital",
  "Avenue Hospital Kisumu",
  "Jaramogi Oginga Odinga Teaching & Referral Hospital",
  "Kakamega County General Hospital",
  "Embu Level 5 Hospital",
  "Machakos Level 5 Hospital",
];

export interface Diagnosis {
  code: string;
  name: string;
}

export const DIAGNOSES: Diagnosis[] = [
  { code: "B54", name: "Malaria, unspecified" },
  { code: "B50.9", name: "Plasmodium falciparum malaria" },
  { code: "I10", name: "Essential (primary) hypertension" },
  { code: "E11.9", name: "Type 2 diabetes mellitus without complications" },
  { code: "E10.9", name: "Type 1 diabetes mellitus without complications" },
  { code: "J18.9", name: "Pneumonia, unspecified organism" },
  { code: "J06.9", name: "Acute upper respiratory infection, unspecified" },
  { code: "A09", name: "Infectious gastroenteritis and colitis" },
  { code: "A01.0", name: "Typhoid fever" },
  { code: "A15.0", name: "Tuberculosis of lung" },
  { code: "B20", name: "HIV disease" },
  { code: "O80", name: "Spontaneous vertex delivery" },
  { code: "O82", name: "Single delivery by caesarean section" },
  { code: "O14.9", name: "Pre-eclampsia, unspecified" },
  { code: "P07.3", name: "Other preterm infants" },
  { code: "S72.0", name: "Fracture of neck of femur" },
  { code: "S52.5", name: "Fracture of lower end of radius" },
  { code: "K35.80", name: "Acute appendicitis" },
  { code: "K80.20", name: "Cholelithiasis with obstruction" },
  { code: "N39.0", name: "Urinary tract infection, site not specified" },
  { code: "N18.6", name: "End stage renal disease" },
  { code: "C50.9", name: "Malignant neoplasm of breast" },
  { code: "C53.9", name: "Malignant neoplasm of cervix uteri" },
  { code: "F32.9", name: "Major depressive disorder, single episode" },
  { code: "G40.909", name: "Epilepsy, unspecified" },
  { code: "I21.9", name: "Acute myocardial infarction" },
  { code: "I63.9", name: "Cerebral infarction (stroke)" },
  { code: "T14.0", name: "Superficial injury of unspecified body region" },
  { code: "R50.9", name: "Fever, unspecified" },
  { code: "Z34.90", name: "Routine antenatal supervision" },
];

export const SERVICES = [
  "Outpatient consultation",
  "Specialist consultation",
  "Full blood count",
  "Malaria rapid diagnostic test",
  "Blood glucose test",
  "HIV screening test",
  "Urinalysis",
  "Lipid profile panel",
  "Chest X-ray",
  "Abdominal ultrasound",
  "Obstetric ultrasound",
  "CT scan — head",
  "MRI — lumbar spine",
  "ECG",
  "Echocardiogram",
  "Minor surgical procedure",
  "Major surgical procedure",
  "Caesarean section",
  "Normal vaginal delivery",
  "Inpatient ward stay (per day)",
  "ICU bed (per day)",
  "Anaesthesia",
  "Physiotherapy session",
  "Dialysis session",
  "Chemotherapy session",
  "Pharmacy — antimalarials",
  "Pharmacy — antibiotics",
  "Pharmacy — antihypertensives",
  "Pharmacy — insulin",
  "Pharmacy — ARV medication",
];

export const KENYAN_NAMES = [
  "Wanjiku Kamau",
  "Otieno Ochieng",
  "Achieng Odhiambo",
  "Mwangi Njoroge",
  "Akinyi Owino",
  "Kiprotich Kosgei",
  "Naliaka Wafula",
  "Mutiso Mbithi",
  "Chebet Sang",
  "Atieno Adhiambo",
];
