/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HospitalPortalRouteImport } from './routes/hospital-portal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardPoliciesRouteImport } from './routes/_authenticated/dashboard.policies'
import { Route as AuthenticatedDashboardInsureesRouteImport } from './routes/_authenticated/dashboard.insurees'
import { Route as AuthenticatedDashboardHospitalsRouteImport } from './routes/_authenticated/dashboard.hospitals'
import { Route as AuthenticatedDashboardFamiliesRouteImport } from './routes/_authenticated/dashboard.families'
import { Route as AuthenticatedDashboardClaimsRouteImport } from './routes/_authenticated/dashboard.claims'
import { Route as AuthenticatedDashboardInsureesIndexRouteImport } from './routes/_authenticated/dashboard.insurees.index'
import { Route as AuthenticatedDashboardHospitalsIndexRouteImport } from './routes/_authenticated/dashboard.hospitals.index'
import { Route as AuthenticatedDashboardFamiliesIndexRouteImport } from './routes/_authenticated/dashboard.families.index'
import { Route as AuthenticatedDashboardPoliciesPolicyIdRouteImport } from './routes/_authenticated/dashboard.policies.$policyId'
import { Route as AuthenticatedDashboardInsureesInsureeIdRouteImport } from './routes/_authenticated/dashboard.insurees.$insureeId'
import { Route as AuthenticatedDashboardHospitalsFacilityIdRouteImport } from './routes/_authenticated/dashboard.hospitals.$facilityId'
import { Route as AuthenticatedDashboardFamiliesFamilyIdRouteImport } from './routes/_authenticated/dashboard.families.$familyId'
import { Route as AuthenticatedDashboardClaimsClaimIdRouteImport } from './routes/_authenticated/dashboard.claims.$claimId'

const HospitalPortalRoute = HospitalPortalRouteImport.update({
  id: '/hospital-portal',
  path: '/hospital-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPoliciesRoute =
  AuthenticatedDashboardPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInsureesRoute =
  AuthenticatedDashboardInsureesRouteImport.update({
    id: '/insurees',
    path: '/insurees',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardHospitalsRoute =
  AuthenticatedDashboardHospitalsRouteImport.update({
    id: '/hospitals',
    path: '/hospitals',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFamiliesRoute =
  AuthenticatedDashboardFamiliesRouteImport.update({
    id: '/families',
    path: '/families',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardClaimsRoute =
  AuthenticatedDashboardClaimsRouteImport.update({
    id: '/claims',
    path: '/claims',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInsureesIndexRoute =
  AuthenticatedDashboardInsureesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardInsureesRoute,
  } as any)
const AuthenticatedDashboardHospitalsIndexRoute =
  AuthenticatedDashboardHospitalsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardHospitalsRoute,
  } as any)
const AuthenticatedDashboardFamiliesIndexRoute =
  AuthenticatedDashboardFamiliesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardFamiliesRoute,
  } as any)
const AuthenticatedDashboardPoliciesPolicyIdRoute =
  AuthenticatedDashboardPoliciesPolicyIdRouteImport.update({
    id: '/$policyId',
    path: '/$policyId',
    getParentRoute: () => AuthenticatedDashboardPoliciesRoute,
  } as any)
const AuthenticatedDashboardInsureesInsureeIdRoute =
  AuthenticatedDashboardInsureesInsureeIdRouteImport.update({
    id: '/$insureeId',
    path: '/$insureeId',
    getParentRoute: () => AuthenticatedDashboardInsureesRoute,
  } as any)
const AuthenticatedDashboardHospitalsFacilityIdRoute =
  AuthenticatedDashboardHospitalsFacilityIdRouteImport.update({
    id: '/$facilityId',
    path: '/$facilityId',
    getParentRoute: () => AuthenticatedDashboardHospitalsRoute,
  } as any)
const AuthenticatedDashboardFamiliesFamilyIdRoute =
  AuthenticatedDashboardFamiliesFamilyIdRouteImport.update({
    id: '/$familyId',
    path: '/$familyId',
    getParentRoute: () => AuthenticatedDashboardFamiliesRoute,
  } as any)
const AuthenticatedDashboardClaimsClaimIdRoute =
  AuthenticatedDashboardClaimsClaimIdRouteImport.update({
    id: '/$claimId',
    path: '/$claimId',
    getParentRoute: () => AuthenticatedDashboardClaimsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hospital-portal': typeof HospitalPortalRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/claims': typeof AuthenticatedDashboardClaimsRouteWithChildren
  '/dashboard/families': typeof AuthenticatedDashboardFamiliesRouteWithChildren
  '/dashboard/hospitals': typeof AuthenticatedDashboardHospitalsRouteWithChildren
  '/dashboard/insurees': typeof AuthenticatedDashboardInsureesRouteWithChildren
  '/dashboard/policies': typeof AuthenticatedDashboardPoliciesRouteWithChildren
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/claims/$claimId': typeof AuthenticatedDashboardClaimsClaimIdRoute
  '/dashboard/families/$familyId': typeof AuthenticatedDashboardFamiliesFamilyIdRoute
  '/dashboard/hospitals/$facilityId': typeof AuthenticatedDashboardHospitalsFacilityIdRoute
  '/dashboard/insurees/$insureeId': typeof AuthenticatedDashboardInsureesInsureeIdRoute
  '/dashboard/policies/$policyId': typeof AuthenticatedDashboardPoliciesPolicyIdRoute
  '/dashboard/families/': typeof AuthenticatedDashboardFamiliesIndexRoute
  '/dashboard/hospitals/': typeof AuthenticatedDashboardHospitalsIndexRoute
  '/dashboard/insurees/': typeof AuthenticatedDashboardInsureesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hospital-portal': typeof HospitalPortalRoute
  '/dashboard/claims': typeof AuthenticatedDashboardClaimsRouteWithChildren
  '/dashboard/policies': typeof AuthenticatedDashboardPoliciesRouteWithChildren
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/claims/$claimId': typeof AuthenticatedDashboardClaimsClaimIdRoute
  '/dashboard/families/$familyId': typeof AuthenticatedDashboardFamiliesFamilyIdRoute
  '/dashboard/hospitals/$facilityId': typeof AuthenticatedDashboardHospitalsFacilityIdRoute
  '/dashboard/insurees/$insureeId': typeof AuthenticatedDashboardInsureesInsureeIdRoute
  '/dashboard/policies/$policyId': typeof AuthenticatedDashboardPoliciesPolicyIdRoute
  '/dashboard/families': typeof AuthenticatedDashboardFamiliesIndexRoute
  '/dashboard/hospitals': typeof AuthenticatedDashboardHospitalsIndexRoute
  '/dashboard/insurees': typeof AuthenticatedDashboardInsureesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/hospital-portal': typeof HospitalPortalRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/claims': typeof AuthenticatedDashboardClaimsRouteWithChildren
  '/_authenticated/dashboard/families': typeof AuthenticatedDashboardFamiliesRouteWithChildren
  '/_authenticated/dashboard/hospitals': typeof AuthenticatedDashboardHospitalsRouteWithChildren
  '/_authenticated/dashboard/insurees': typeof AuthenticatedDashboardInsureesRouteWithChildren
  '/_authenticated/dashboard/policies': typeof AuthenticatedDashboardPoliciesRouteWithChildren
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/claims/$claimId': typeof AuthenticatedDashboardClaimsClaimIdRoute
  '/_authenticated/dashboard/families/$familyId': typeof AuthenticatedDashboardFamiliesFamilyIdRoute
  '/_authenticated/dashboard/hospitals/$facilityId': typeof AuthenticatedDashboardHospitalsFacilityIdRoute
  '/_authenticated/dashboard/insurees/$insureeId': typeof AuthenticatedDashboardInsureesInsureeIdRoute
  '/_authenticated/dashboard/policies/$policyId': typeof AuthenticatedDashboardPoliciesPolicyIdRoute
  '/_authenticated/dashboard/families/': typeof AuthenticatedDashboardFamiliesIndexRoute
  '/_authenticated/dashboard/hospitals/': typeof AuthenticatedDashboardHospitalsIndexRoute
  '/_authenticated/dashboard/insurees/': typeof AuthenticatedDashboardInsureesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/hospital-portal'
    | '/dashboard'
    | '/dashboard/claims'
    | '/dashboard/families'
    | '/dashboard/hospitals'
    | '/dashboard/insurees'
    | '/dashboard/policies'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/claims/$claimId'
    | '/dashboard/families/$familyId'
    | '/dashboard/hospitals/$facilityId'
    | '/dashboard/insurees/$insureeId'
    | '/dashboard/policies/$policyId'
    | '/dashboard/families/'
    | '/dashboard/hospitals/'
    | '/dashboard/insurees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/hospital-portal'
    | '/dashboard/claims'
    | '/dashboard/policies'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/claims/$claimId'
    | '/dashboard/families/$familyId'
    | '/dashboard/hospitals/$facilityId'
    | '/dashboard/insurees/$insureeId'
    | '/dashboard/policies/$policyId'
    | '/dashboard/families'
    | '/dashboard/hospitals'
    | '/dashboard/insurees'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/hospital-portal'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/claims'
    | '/_authenticated/dashboard/families'
    | '/_authenticated/dashboard/hospitals'
    | '/_authenticated/dashboard/insurees'
    | '/_authenticated/dashboard/policies'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/claims/$claimId'
    | '/_authenticated/dashboard/families/$familyId'
    | '/_authenticated/dashboard/hospitals/$facilityId'
    | '/_authenticated/dashboard/insurees/$insureeId'
    | '/_authenticated/dashboard/policies/$policyId'
    | '/_authenticated/dashboard/families/'
    | '/_authenticated/dashboard/hospitals/'
    | '/_authenticated/dashboard/insurees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HospitalPortalRoute: typeof HospitalPortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hospital-portal': {
      id: '/hospital-portal'
      path: '/hospital-portal'
      fullPath: '/hospital-portal'
      preLoaderRoute: typeof HospitalPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/policies': {
      id: '/_authenticated/dashboard/policies'
      path: '/policies'
      fullPath: '/dashboard/policies'
      preLoaderRoute: typeof AuthenticatedDashboardPoliciesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/insurees': {
      id: '/_authenticated/dashboard/insurees'
      path: '/insurees'
      fullPath: '/dashboard/insurees'
      preLoaderRoute: typeof AuthenticatedDashboardInsureesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/hospitals': {
      id: '/_authenticated/dashboard/hospitals'
      path: '/hospitals'
      fullPath: '/dashboard/hospitals'
      preLoaderRoute: typeof AuthenticatedDashboardHospitalsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/families': {
      id: '/_authenticated/dashboard/families'
      path: '/families'
      fullPath: '/dashboard/families'
      preLoaderRoute: typeof AuthenticatedDashboardFamiliesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/claims': {
      id: '/_authenticated/dashboard/claims'
      path: '/claims'
      fullPath: '/dashboard/claims'
      preLoaderRoute: typeof AuthenticatedDashboardClaimsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/insurees/': {
      id: '/_authenticated/dashboard/insurees/'
      path: '/'
      fullPath: '/dashboard/insurees/'
      preLoaderRoute: typeof AuthenticatedDashboardInsureesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardInsureesRoute
    }
    '/_authenticated/dashboard/hospitals/': {
      id: '/_authenticated/dashboard/hospitals/'
      path: '/'
      fullPath: '/dashboard/hospitals/'
      preLoaderRoute: typeof AuthenticatedDashboardHospitalsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardHospitalsRoute
    }
    '/_authenticated/dashboard/families/': {
      id: '/_authenticated/dashboard/families/'
      path: '/'
      fullPath: '/dashboard/families/'
      preLoaderRoute: typeof AuthenticatedDashboardFamiliesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardFamiliesRoute
    }
    '/_authenticated/dashboard/policies/$policyId': {
      id: '/_authenticated/dashboard/policies/$policyId'
      path: '/$policyId'
      fullPath: '/dashboard/policies/$policyId'
      preLoaderRoute: typeof AuthenticatedDashboardPoliciesPolicyIdRouteImport
      parentRoute: typeof AuthenticatedDashboardPoliciesRoute
    }
    '/_authenticated/dashboard/insurees/$insureeId': {
      id: '/_authenticated/dashboard/insurees/$insureeId'
      path: '/$insureeId'
      fullPath: '/dashboard/insurees/$insureeId'
      preLoaderRoute: typeof AuthenticatedDashboardInsureesInsureeIdRouteImport
      parentRoute: typeof AuthenticatedDashboardInsureesRoute
    }
    '/_authenticated/dashboard/hospitals/$facilityId': {
      id: '/_authenticated/dashboard/hospitals/$facilityId'
      path: '/$facilityId'
      fullPath: '/dashboard/hospitals/$facilityId'
      preLoaderRoute: typeof AuthenticatedDashboardHospitalsFacilityIdRouteImport
      parentRoute: typeof AuthenticatedDashboardHospitalsRoute
    }
    '/_authenticated/dashboard/families/$familyId': {
      id: '/_authenticated/dashboard/families/$familyId'
      path: '/$familyId'
      fullPath: '/dashboard/families/$familyId'
      preLoaderRoute: typeof AuthenticatedDashboardFamiliesFamilyIdRouteImport
      parentRoute: typeof AuthenticatedDashboardFamiliesRoute
    }
    '/_authenticated/dashboard/claims/$claimId': {
      id: '/_authenticated/dashboard/claims/$claimId'
      path: '/$claimId'
      fullPath: '/dashboard/claims/$claimId'
      preLoaderRoute: typeof AuthenticatedDashboardClaimsClaimIdRouteImport
      parentRoute: typeof AuthenticatedDashboardClaimsRoute
    }
  }
}

interface AuthenticatedDashboardClaimsRouteChildren {
  AuthenticatedDashboardClaimsClaimIdRoute: typeof AuthenticatedDashboardClaimsClaimIdRoute
}

const AuthenticatedDashboardClaimsRouteChildren: AuthenticatedDashboardClaimsRouteChildren =
  {
    AuthenticatedDashboardClaimsClaimIdRoute:
      AuthenticatedDashboardClaimsClaimIdRoute,
  }

const AuthenticatedDashboardClaimsRouteWithChildren =
  AuthenticatedDashboardClaimsRoute._addFileChildren(
    AuthenticatedDashboardClaimsRouteChildren,
  )

interface AuthenticatedDashboardFamiliesRouteChildren {
  AuthenticatedDashboardFamiliesFamilyIdRoute: typeof AuthenticatedDashboardFamiliesFamilyIdRoute
  AuthenticatedDashboardFamiliesIndexRoute: typeof AuthenticatedDashboardFamiliesIndexRoute
}

const AuthenticatedDashboardFamiliesRouteChildren: AuthenticatedDashboardFamiliesRouteChildren =
  {
    AuthenticatedDashboardFamiliesFamilyIdRoute:
      AuthenticatedDashboardFamiliesFamilyIdRoute,
    AuthenticatedDashboardFamiliesIndexRoute:
      AuthenticatedDashboardFamiliesIndexRoute,
  }

const AuthenticatedDashboardFamiliesRouteWithChildren =
  AuthenticatedDashboardFamiliesRoute._addFileChildren(
    AuthenticatedDashboardFamiliesRouteChildren,
  )

interface AuthenticatedDashboardHospitalsRouteChildren {
  AuthenticatedDashboardHospitalsFacilityIdRoute: typeof AuthenticatedDashboardHospitalsFacilityIdRoute
  AuthenticatedDashboardHospitalsIndexRoute: typeof AuthenticatedDashboardHospitalsIndexRoute
}

const AuthenticatedDashboardHospitalsRouteChildren: AuthenticatedDashboardHospitalsRouteChildren =
  {
    AuthenticatedDashboardHospitalsFacilityIdRoute:
      AuthenticatedDashboardHospitalsFacilityIdRoute,
    AuthenticatedDashboardHospitalsIndexRoute:
      AuthenticatedDashboardHospitalsIndexRoute,
  }

const AuthenticatedDashboardHospitalsRouteWithChildren =
  AuthenticatedDashboardHospitalsRoute._addFileChildren(
    AuthenticatedDashboardHospitalsRouteChildren,
  )

interface AuthenticatedDashboardInsureesRouteChildren {
  AuthenticatedDashboardInsureesInsureeIdRoute: typeof AuthenticatedDashboardInsureesInsureeIdRoute
  AuthenticatedDashboardInsureesIndexRoute: typeof AuthenticatedDashboardInsureesIndexRoute
}

const AuthenticatedDashboardInsureesRouteChildren: AuthenticatedDashboardInsureesRouteChildren =
  {
    AuthenticatedDashboardInsureesInsureeIdRoute:
      AuthenticatedDashboardInsureesInsureeIdRoute,
    AuthenticatedDashboardInsureesIndexRoute:
      AuthenticatedDashboardInsureesIndexRoute,
  }

const AuthenticatedDashboardInsureesRouteWithChildren =
  AuthenticatedDashboardInsureesRoute._addFileChildren(
    AuthenticatedDashboardInsureesRouteChildren,
  )

interface AuthenticatedDashboardPoliciesRouteChildren {
  AuthenticatedDashboardPoliciesPolicyIdRoute: typeof AuthenticatedDashboardPoliciesPolicyIdRoute
}

const AuthenticatedDashboardPoliciesRouteChildren: AuthenticatedDashboardPoliciesRouteChildren =
  {
    AuthenticatedDashboardPoliciesPolicyIdRoute:
      AuthenticatedDashboardPoliciesPolicyIdRoute,
  }

const AuthenticatedDashboardPoliciesRouteWithChildren =
  AuthenticatedDashboardPoliciesRoute._addFileChildren(
    AuthenticatedDashboardPoliciesRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardClaimsRoute: typeof AuthenticatedDashboardClaimsRouteWithChildren
  AuthenticatedDashboardFamiliesRoute: typeof AuthenticatedDashboardFamiliesRouteWithChildren
  AuthenticatedDashboardHospitalsRoute: typeof AuthenticatedDashboardHospitalsRouteWithChildren
  AuthenticatedDashboardInsureesRoute: typeof AuthenticatedDashboardInsureesRouteWithChildren
  AuthenticatedDashboardPoliciesRoute: typeof AuthenticatedDashboardPoliciesRouteWithChildren
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardClaimsRoute:
      AuthenticatedDashboardClaimsRouteWithChildren,
    AuthenticatedDashboardFamiliesRoute:
      AuthenticatedDashboardFamiliesRouteWithChildren,
    AuthenticatedDashboardHospitalsRoute:
      AuthenticatedDashboardHospitalsRouteWithChildren,
    AuthenticatedDashboardInsureesRoute:
      AuthenticatedDashboardInsureesRouteWithChildren,
    AuthenticatedDashboardPoliciesRoute:
      AuthenticatedDashboardPoliciesRouteWithChildren,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HospitalPortalRoute: HospitalPortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
